apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop

type: Opaque

stringData:
  NEXTAUTH_SECRET: "QWm03teVpyKeNu1zPQWcXe9YgSVN9Oct5/hx+28x+/I="
  JWT_SECRET: "f6caa9f1eef1e36aadef8c43043476573eb3e5daa8be051a33be0ff87a833804"